/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/help`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/crypto` | `/crypto`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/invest` | `/invest`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/lifestyle` | `/lifestyle`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/transfer` | `/transfer`; params?: Router.UnknownInputParams; } | { pathname: `/verify/[phone]`, params: Router.UnknownInputParams & { phone: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/help`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/crypto` | `/crypto`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/invest` | `/invest`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/lifestyle` | `/lifestyle`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/transfer` | `/transfer`; params?: Router.UnknownOutputParams; } | { pathname: `/verify/[phone]`, params: Router.UnknownOutputParams & { phone: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/help${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}${'/(tabs)'}/crypto${`?${string}` | `#${string}` | ''}` | `/crypto${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}${'/(tabs)'}/invest${`?${string}` | `#${string}` | ''}` | `/invest${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}${'/(tabs)'}/lifestyle${`?${string}` | `#${string}` | ''}` | `/lifestyle${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}${'/(tabs)'}/transfer${`?${string}` | `#${string}` | ''}` | `/transfer${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/help`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/crypto` | `/crypto`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/invest` | `/invest`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/lifestyle` | `/lifestyle`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}${'/(tabs)'}/transfer` | `/transfer`; params?: Router.UnknownInputParams; } | `/verify/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/verify/[phone]`, params: Router.UnknownInputParams & { phone: string | number; } };
    }
  }
}
